routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('client.index');

//login
Route::get('login', 'UserController@login')->name('login');
Route::post('login', 'UserController@checkLogin')->name('login.post');
Route::get('logout', 'UserController@logout')->name('logout');
Route::patch('settingUser/{id}', 'UserController@update')->middleware('login')->name('user.update');

Route::group(['prefix' => 'admin', 'middleware' => 'login'], function () {
    //Overview
    Route::get('/', 'OverviewController@index')->name('overview');

    //Category
    Route::resource('categories', 'CategoryController');
    Route::get('searchCategories', 'CategoryController@search')->name('category.search');

    //Brand
    Route::resource('brands', 'BrandController');
    Route::post('brands/{id}', 'BrandController@editWith')->name('brands.delete');
    Route::get('searchBrands', 'BrandController@search')->name('brands.search');

    //product
    Route::resource('products', 'ProductController');
    Route::get('searchProducts', 'ProductController@search')->name('products.search');
    Route::post('products/restore/{id}', 'ProductController@restore')->name('products.restore');
    Route::post('products/realDelete/{id}', 'ProductController@realDelete')->name('products.realDelete');

    //image
    Route::resource('images', 'ImageController');
    Route::post('images/updateImages/{id}', 'ImageController@updateImages')->name('images.update');
    Route::post('images/uploadMultiImage', 'ImageController@postImage')->name('images.uploadMultiImage');

    //customer
    Route::resource('customers', 'CustomerController');
    Route::get('searchCustomers', 'CustomerController@search')->name('customers.search');

    //order
    Route::resource('orders', 'OrderController');
    Route::get('searchOrders', 'OrderController@search')->name('orders.search');

    //overview
    Route::post('overview/getOrdersOnDay', 'OverviewController@getResourcesOn')->name('overview.getOnDay');

});

resources/views/admins/layout/footer.blade.php
<footer>
    <div class="pull-right">
        Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
    </div>
    <div class="clearfix"></div>
</footer>

resources/views/admins/layout/leftMenu.blade.php
<div class="col-md-3 left_col menu_fixed">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Shose Shop</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <span class="glyphicon glyphicon-user" aria-hidden="true" style="font-size: 60px"></span>
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2 class="userName">{{ Auth::user()->name }}</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                    <li><a href="{{ route('overview') }}"><i class="fa fa-home"></i> Home </a></li>
                    <li><a href="{{ route('categories.index') }}"><i class="fa fa-th-list"></i>Categories</a></li>
                    <li><a href="{{ route('brands.index') }}"><i class="fa fa-truck"></i> Brands</a></li>
                    <li><a href="{{ route('products.index') }}"><i class="fa fa-gift"></i> Products </a></li>
                    <li><a href="{{ route('customers.index') }}"><i class="fa fa-male"></i> Customers </a></li>
                    <li><a href="{{ route('orders.index') }}"><i class="fa fa-shopping-cart"></i>Orders</a></li>
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small" style="background-color: #172D44">
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>

resources/views/admins/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{{ asset('images/favicon.ico') }}" type="image/ico"/>

    <title>@yield('title')</title>

    <link href="{{ asset('vendors/switchery/dist/switchery.min.css') }}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{{ asset('vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{ asset('vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{{ asset('vendors/nprogress/nprogress.css') }}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{{ asset('vendors/iCheck/skins/flat/green.css') }}" rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="{{ asset('vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css') }}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{{ asset('vendors/jqvmap/dist/jqvmap.min.css') }}" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="{{ asset('vendors/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
    <!-- jQuery custom content scroller -->
    <link href="{{ asset('vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css') }}"
          rel="stylesheet"/>
    <!-- Custom Theme Style -->
    <link href="{{ asset('build/css/custom.min.css') }}" rel="stylesheet">
    <link href="{{ asset('build/css/custom.css') }}" rel="stylesheet">

    {{--    data table--}}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">

</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
    @include('admins.layout.leftMenu')

    <!-- top navigation -->
    @include('admins.layout.navigation')
    <!-- /top navigation -->

        <!-- page content -->
    @yield('content')
    <!-- /page content -->
        <!-- footer content -->
    @include('admins.layout.footer')
    <!-- /footer content -->
    </div>
</div>

<!-- number format -->
<script src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>
<!-- jQuery -->
<script src="{{ asset('vendors/jquery/dist/jquery.min.js') }}"></script>
<!--BaseScript-->
<script src="{{ asset('build/js/baseScript.js') }}"></script>
<!-- Bootstrap -->
<script src="{{ asset('vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('vendors/fastclick/lib/fastclick.js') }}"></script>
<!-- NProgress -->
<script src="{{ asset('vendors/nprogress/nprogress.js') }}"></script>
<!-- Chart.js -->
<script src="{{ asset('vendors/Chart.js/dist/Chart.min.js') }}"></script>
<!-- gauge.js -->
<script src="{{ asset('vendors/gauge.js/dist/gauge.min.js') }}"></script>
<!-- bootstrap-progressbar -->
<script src="{{ asset('vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
<!-- iCheck -->
<script src="{{ asset('vendors/iCheck/icheck.min.js') }}"></script>
<!-- Skycons -->
<script src="{{ asset('vendors/skycons/skycons.js') }}"></script>
<!-- Flot -->
<script src="{{ asset('vendors/Flot/jquery.flot.js') }}"></script>
<script src="{{ asset('vendors/Flot/jquery.flot.pie.js') }}"></script>
<script src="{{ asset('vendors/Flot/jquery.flot.time.js') }}"></script>
<script src="{{ asset('vendors/Flot/jquery.flot.stack.js') }}"></script>
<script src="{{ asset('vendors/Flot/jquery.flot.resize.js') }}"></script>
<!-- Flot plugins -->
<script src="{{ asset('vendors/flot.orderbars/js/jquery.flot.orderBars.js') }}"></script>
<script src="{{ asset('vendors/flot-spline/js/jquery.flot.spline.min.js') }}"></script>
<script src="{{ asset('vendors/flot.curvedlines/curvedLines.js') }}"></script>
<!-- DateJS -->
<script src="{{ asset('vendors/DateJS/build/date.js') }}"></script>
<!-- JQVMap -->
<script src="{{ asset('vendors/jqvmap/dist/jquery.vmap.js') }}"></script>
<script src="{{ asset('vendors/jqvmap/dist/maps/jquery.vmap.world.js') }}"></script>
<script src="{{ asset('vendors/jqvmap/examples/js/jquery.vmap.sampledata.js') }}"></script>
<!-- bootstrap-daterangepicker -->
<script src="{{ asset('vendors/moment/min/moment.min.js') }}"></script>
<script src="{{ asset('vendors/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<!-- Custom Theme Scripts -->
<script src="{{ asset('build/js/custom.min.js') }}"></script>

{{--data table--}}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
<!--sweetalert-->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<!--Javascript of content-->
@yield('script')

{{--js setting user--}}
<script>
    $('#updateUser').click(function (event) {
        event.preventDefault();
        let dataResource = $('#settingUserForm').serialize();
        let url = '/settingUser/' + {{ Auth::user()->id }};
        callAjax(url, 'patch', dataResource)
            .done(response => {
                Swal.fire({
                    icon: 'success',
                    title: 'OK',
                    text: response.message,
                })
                    .then((result) => {
                        $('.userName').text(response.data.name);
                    })
            })
            .fail(error => {
                show_error_and_focus_on_form('-setting-form', error.responseJSON.errors);
                showErrorMessage('Opp!', 'Update category fail');
            })
    })
</script>
</body>
</html>

resources/views/admins/layout/navigation.blade.php
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <span class="glyphicon glyphicon-user userName" aria-hidden="true" style="font-size: 20px"> {{ Auth::user()->name }}</span>
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li>
                            <a href="javascript:">
                                <a data-toggle="modal"
                                        data-target=".bs-example-modal-lg-setting"> Setting
                                </a>
                            </a>
                        </li>
                        <li><a href="{{ route('logout') }}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                    </ul>
                </li>
            </ul>

            <div class="modal fade bs-example-modal-lg-setting" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span
                                    aria-hidden="true">×</span>
                            </button>
                            <h4 class="modal-title" id="myModalLabel">Setting</h4>
                        </div>
                        <div class="modal-body">
                            <form class="form-horizontal form-label-left" id="settingUserForm">
                                @csrf
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
                                    <div class="col-md-9 col-sm-9 col-xs-12">
                                        <input type="text" class="form-control"
                                               placeholder="Name of new category" name="name" id="input-name-setting-form" value="{{ Auth::user()->name }}">
                                        <p class="error" style="color: red" id="error-name-setting-form"></p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Email</label>
                                    <div class="col-md-9 col-sm-9 col-xs-12">
                                        <input type="text" class="form-control"
                                               placeholder="email of new category" name="email" id="input-email-setting-form" value="{{ Auth::user()->email }}">
                                        <p class="error" style="color: red" id="error-email-setting-form"></p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label
                                        class="control-label col-md-3 col-sm-3 col-xs-12">Old password</label>
                                    <div class="col-md-9 col-sm-9 col-xs-12">
                                                    <input type="password" class="form-control" rows="3"
                                                              name="oldPassword" id="input-oldPassword-setting-form">
                                        <p class="error" style="color: red" id="error-oldPassword-setting-form"></p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label
                                        class="control-label col-md-3 col-sm-3 col-xs-12">New password</label>
                                    <div class="col-md-9 col-sm-9 col-xs-12">
                                        <input type="password" class="form-control" rows="3"
                                               name="newPassword" id="input-newPassword-setting-form">
                                        <p class="error" style="color: red" id="error-newPassword-setting-form"></p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label
                                        class="control-label col-md-3 col-sm-3 col-xs-12">Confirm new password</label>
                                    <div class="col-md-9 col-sm-9 col-xs-12">
                                        <input type="password" class="form-control" rows="3"
                                               name="newPassword_confirmation" id="input-newPassword_confirmation-setting-form">
                                        <p class="error" style="color: red" id="error-newPassword_confirmation-setting-form"></p>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                                        <button type="button" class="btn btn-primary" data-dismiss="modal">
                                            Cancel
                                        </button>
                                        <button type="reset" class="btn btn-primary">Reset</button>
                                        <button type="button" class="btn btn-success" id="updateUser">
                                            Submit
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</div>