routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('client.index');

//login
Route::get('login', 'UserController@login')->name('login');
Route::post('login', 'UserController@checkLogin')->name('login.post');
Route::get('logout', 'UserController@logout')->name('logout');
Route::patch('settingUser/{id}', 'UserController@update')->middleware('login')->name('user.update');

Route::group(['prefix' => 'admin', 'middleware' => 'login'], function () {
    //Overview
    Route::get('/', 'OverviewController@index')->name('overview');

    //Category
    Route::resource('categories', 'CategoryController');
    Route::get('searchCategories', 'CategoryController@search')->name('category.search');

    //Brand
    Route::resource('brands', 'BrandController');
    Route::post('brands/{id}', 'BrandController@editWith')->name('brands.delete');
    Route::get('searchBrands', 'BrandController@search')->name('brands.search');

    //product
    Route::resource('products', 'ProductController');
    Route::get('searchProducts', 'ProductController@search')->name('products.search');
    Route::post('products/restore/{id}', 'ProductController@restore')->name('products.restore');
    Route::post('products/realDelete/{id}', 'ProductController@realDelete')->name('products.realDelete');

    //image
    Route::resource('images', 'ImageController');
    Route::post('images/updateImages/{id}', 'ImageController@updateImages')->name('images.update');
    Route::post('images/uploadMultiImage', 'ImageController@postImage')->name('images.uploadMultiImage');

    //customer
    Route::resource('customers', 'CustomerController');
    Route::get('searchCustomers', 'CustomerController@search')->name('customers.search');

    //order
    Route::resource('orders', 'OrderController');
    Route::get('searchOrders', 'OrderController@search')->name('orders.search');

    //overview
    Route::post('overview/getOrdersOnDay', 'OverviewController@getResourcesOn')->name('overview.getOnDay');

});

app/Product.php
<?php

namespace App;

use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Product extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'description',
        'number_of',
        'price',
        'product_image_id',
        'brand_id',
        'category_id',
    ];

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function brand()
    {
        return $this->belongsTo('App\Brand');
    }

    public function images()
    {
        return $this->hasMany('App\Image');
    }

    public function orders()
    {
        return $this->belongsToMany('App\Order')->withPivot('number_of_product')->withTimestamps();
    }

    /**
     * @return LengthAwarePaginator
     */
    public function getAllResource()
    {
        $resources = $this->withTrashed()->latest()->paginate(5);
        return $resources;
    }

    /**
     * @param $id
     * @return Product|Product[]|Builder|Builder[]|Collection|Model|\Illuminate\Database\Query\Builder|\Illuminate\Database\Query\Builder[]
     */
    public function getResourceBy($id)
    {
        $resource = $this->withTrashed()->findOrFail($id);
        return $resource;
    }

    /**
     * @param $data
     * @return LengthAwarePaginator
     */
    public function getResourcesBy($data)
    {
        $name = $data['name'];
        $description = $data['description'];
        $category = $data['category'];
        $brand = $data['brand'];
        $softDelete = isset($data['softDelete']) ? $data['softDelete'][0] : null;

        if ($softDelete == null) {
            $resources = DB::table('products')
                ->join('images', 'products.id', '=', 'images.product_id')
                ->join('brands', 'products.brand_id', '=', 'brands.id')
                ->join('categories', 'products.category_id', '=', 'categories.id')
                ->where('images.status', '1')
                ->where('products.deleted_at', '=', null)
                ->where('products.name', 'like', '%' . $name . '%')
                ->where('products.description', 'like', '%' . $description . '%')
                ->where('brands.name', 'like', '%' . $brand . '%')
                ->where('categories.name', 'like', '%' . $category . '%')
                ->select(['brands.name AS brand_name', 'categories.name AS category_name', 'products.*', 'images.name AS image_name'])
                ->latest('products.created_at')
                ->paginate(5);
        }
        if ($softDelete != null) {
            $resources = DB::table('products')
                ->join('images', 'products.id', '=', 'images.product_id')
                ->join('brands', 'products.brand_id', '=', 'brands.id')
                ->join('categories', 'products.category_id', '=', 'categories.id')
                ->where('images.status', '1')
                ->where('products.deleted_at', '<>', null)
                ->where('products.name', 'like', '%' . $name . '%')
                ->where('products.description', 'like', '%' . $description . '%')
                ->where('brands.name', 'like', '%' . $brand . '%')
                ->where('categories.name', 'like', '%' . $category . '%')
                ->select(['brands.name AS brand_name', 'categories.name AS category_name', 'products.*', 'images.name AS image_name'])
                ->latest('products.created_at')
                ->paginate(5);
        }

        return $resources;
    }

    /**
     * function check number of product and number sell
     * @param $id
     * @param $numberSell
     * @return bool
     */
    public function checkNumberOf($id, $numberSell)
    {
        $product = $this->findOrFail($id);
        $oldNumber = $product->number_of;
        if($oldNumber >= $numberSell) {
            return true;
        }else
            return false;
    }

    /**
     * function update number of product before sell
     * @param $id
     * @param $numberSell
     * @return void
     */
    public function updateNumberOf($id, $numberSell)
    {
        $product = $this->findOrFail($id);
        $oldNumber = $product->number_of;
        $product->update(['number_of' => $oldNumber - $numberSell]);
    }

    /**
     * function get arr top seller product
     * @param $limit
     * @return \Illuminate\Support\Collection
     */
    public function topSeller($limit)
    {
        $topSeller = DB::table('order_product')
            ->join('products', 'product_id', '=', 'products.id')
            ->join('images', 'products.id', '=', 'images.product_id')
            ->where('images.status', '=', 1)
            ->select('products.name', 'products.price', 'images.name AS image_name', DB::raw('SUM(number_of_product) as number_sell'))
            ->groupBy('products.name')
            ->groupBy('image_name')
            ->groupBy('price')
            ->latest('number_sell')
            ->take($limit)
            ->get();
        return $topSeller;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Brand;
use App\Category;
use App\Http\Requests\ProductRequest;
use App\Http\Traits\ImageTrait;
use App\Image;
use App\Product;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;

class ProductController extends Controller
{
    use ImageTrait;

    protected $product;

    public function __construct(Product $product)
    {
        $this->product = $product;
    }

    /**
     * @return Factory|View
     */
    public function index()
    {
        $resources = $this->product->getAllResource();
        return view('admins.product.product', ['resources' => $resources]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        $categories = Category::all();
        $brands = Brand::all();
        return view('admins.product.createProduct', ['categories' => $categories, 'brands' => $brands]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(ProductRequest $request)
    {
        $dataProduct = [
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'number_of' => $request->input('number_of'),
            'price' => $request->input('price'),
            'category_id' => $request->input('category'),
            'brand_id' => $request->input('brand'),
        ];
        $response = $this->product->create($dataProduct);

        $dataImage = [];
        $dataImage['product_id'] = $response->id;
        $mainImage = $request->input('mainImage');
        $dataImage['imagesUploaed'] = $this->uploadMultiImageWith($request->file('images'), $mainImage);
        if (isset($dataImage['imagesUploaed']['nomarImage']))
            foreach ($dataImage['imagesUploaed']['nomarImage'] as $nomarImage => $value) {
                $dataNewEmage = [
                    'name' => $value,
                    'product_id' => $dataImage['product_id'],
                    'status' => 0
                ];
                Image::create($dataNewEmage);
            }
        $dataNewMainEmage = [
            'name' => $dataImage['imagesUploaed']['mainImage'][0],
            'product_id' => $dataImage['product_id'],
            'status' => 1
        ];
        Image::create($dataNewMainEmage);

        session(['succesful' => 'Create the product succesful']);
        return redirect()->back()->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Factory|View
     */
    public function edit($id)
    {
        $categories = Category::all();
        $brands = Brand::all();
        $resource = $this->product->getResourceBy($id);
        return view('admins.product.editProduct', ['idProduct' => $id, 'resource' => $resource, 'categories' => $categories, 'brands' => $brands]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(ProductRequest $request, $id)
    {
        $product = $this->product->findOrFail($id);
        $product->update($request->all());
        session(['successful' => 'Update the product successful']);
        return redirect()->back()->withInput();
    }

    /**
     * @param $id
     * @return JsonResponse
     */
    public function destroy($id)
    {
        $product = $this->product->findOrFail($id);
        $product->delete();
        return response()->json([
            'statusCode' => '200',
            'message' => 'Soft delete successful',
            'data' => $product
        ], 200);
    }

    /**
     * @param $id
     * @return JsonResponse
     */
    public function realDelete($id)
    {
        $product = $this->product->findOrFail($id);
        $images = Image::where('product_id', $id)->get('name');
        $deleteImages = $this->deleteMultiImageIn($images);
        if ($deleteImages) {
            $product->forceDelete();
            return response()->json([
                'statusCode' => '200',
                'message' => 'Real delete successful',
                'data' => $product
            ], 200);
        } else
            return response()->json([
                'statusCode' => '500',
                'message' => 'Real delete is fail',
                'data' => $product
            ], 500);
    }

    /**
     * @param Request $request
     * @return Factory|View
     */
    public function search(Request $request)
    {
        $request->flash();
        $resources = $this->product->getResourcesBy($request->all());
        return view('admins.product.product', ['resources' => $resources]);
    }

    /**
     * @param $id
     * @return JsonResponse
     */
    public function restore($id)
    {
        $product = $this->product->withTrashed()->findOrFail($id);
        $product->restore();
        return response()->json([
            'statusCode' => '200',
            'message' => 'Restore successful',
            'data' => $product
        ], 200);
    }
}

resources/views/admins/product/createProduct.blade.php
@extends('admins.layout.master')

@section('title')
    Create product
@endsection

@section('content')
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <div class="url">
                        <a href="{{ route('products.index') }}"><h3>Product</h3></a>
                        <a href="{{ route('products.create') }}"><h4>Create</h4></a>
                    </div>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Infor product </h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <br>
                            <?php
                            if (Session::has('errors'))
                                $error = Session::get('errors')->default->messages();
                            ?>
                            <form class="form-horizontal form-label-left" action="{{ route('products.store') }}"
                                  method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-xs-6">
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Category</label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <select class="form-control" name="category" id="input-category">
                                                    @foreach($categories as $category)
                                                        <option
                                                            value="{{ $category->id }}"
                                                            @if(old('category') == $category->id) selected='selected' @endif>{{ $category->name }}</option>
                                                    @endforeach
                                                </select>
                                                @if(isset($error['category']))
                                                    <div>
                                                        <p class="errorMessage">{{ $error['category'][0] }}</p>
                                                    </div>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Brand</label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <select class="form-control" name="brand" id="input-brand">
                                                    @foreach($brands as $brand)
                                                        <option value="{{ $brand->id }}"
                                                                @if(old('brand') == $brand->id) selected='selected' @endif>{{ $brand->name }}</option>
                                                    @endforeach
                                                </select>
                                                @if(isset($error['brand']))
                                                    <div>
                                                        <p class="errorMessage">{{ $error['brand'][0] }}</p>
                                                    </div>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Name</label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <input type="text" class="form-control" placeholder="Default Input"
                                                       name="name" id="input-name" value="{{ old('name') }}">
                                                @if(isset($error['name']))
                                                    <div>
                                                        <p class="errorMessage">{{ $error['name'][0] }}</p>
                                                    </div>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Description</label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <textarea class="form-control" rows="3"
                                                          placeholder="description of new product"
                                                          name="description"
                                                          id="input-description">{{ old('description') }}</textarea>
                                                @if(isset($error['description']))
                                                    <div>
                                                        <p class="errorMessage">{{ $error['description'][0] }}</p>
                                                    </div>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Number of
                                                product</label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <input type="number" class="form-control"
                                                       name="number_of" id="input-number_off"
                                                       value="{{ old('number_of') }}">
                                                @if(isset($error['number_of']))
                                                    <div>
                                                        <p class="errorMessage">{{ $error['number_of'][0] }}</p>
                                                    </div>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Price</label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <input type="number" class="form-control"
                                                       name="price" id="input-number_off"
                                                       value="{{ old('price') }}">
                                                @if(isset($error['price']))
                                                    <div>
                                                        <p class="errorMessage">{{ $error['price'][0] }}</p>
                                                    </div>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-xs-6">
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">List image</label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <input type="file" class="form-control" name="images[]"
                                                       id="input-image-create-form" multiple id="input-images"
                                                       value="{{ old('images') }}">
                                                @if(isset($error['images']))
                                                    <div>
                                                        <p class="errorMessage">{{ $error['images'][0] }}</p>
                                                    </div>
                                                @endif
                                                @if(isset($error['images.0']))
                                                <div>
                                                    <p class="errorMessage">{{ $error['images.0'][0] }}</p>
                                                </div>
                                                @endif
                                            </div>
                                            <div class="col-md-12 col-sm-12 col-xs-12 row" id="preview-list-image">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Main image</label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <select class="form-control" name="mainImage" id="selectMainImageForProduct">
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <center>
                                        <div>
                                            <button type="reset" class="btn btn-primary">Reset</button>
                                            <button type="submit" class="btn btn-success">Submit</button>
                                        </div>
                                    </center>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('build/js/product.js') }}"></script>
    @if(Session::has('errors'))
        <script>
            var isHasSession = '{{ Session::has('errors') }}';
            if (isHasSession) {
                var arrError = [
                        @foreach ($error as $key => $value)
                    ["{{ $key }}", "{{ $value[0] }}"],
                    @endforeach
                ];
                $('#input-' + arrError[0][0]).focus();
                console.log(arrError);
            }
        </script>
    @endif

    @if(Session::has('succesful'))
        <script>
            Swal.fire({
                position: 'top',
                icon: 'success',
                title: '{{ Session::pull('succesful') }}',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
    @endif
@endsection