routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('client.index');

//login
Route::get('login', 'UserController@login')->name('login');
Route::post('login', 'UserController@checkLogin')->name('login.post');
Route::get('logout', 'UserController@logout')->name('logout');
Route::patch('settingUser/{id}', 'UserController@update')->middleware('login')->name('user.update');

Route::group(['prefix' => 'admin', 'middleware' => 'login'], function () {
    //Overview
    Route::get('/', 'OverviewController@index')->name('overview');

    //Category
    Route::resource('categories', 'CategoryController');
    Route::get('searchCategories', 'CategoryController@search')->name('category.search');

    //Brand
    Route::resource('brands', 'BrandController');
    Route::post('brands/{id}', 'BrandController@editWith')->name('brands.delete');
    Route::get('searchBrands', 'BrandController@search')->name('brands.search');

    //product
    Route::resource('products', 'ProductController');
    Route::get('searchProducts', 'ProductController@search')->name('products.search');
    Route::post('products/restore/{id}', 'ProductController@restore')->name('products.restore');
    Route::post('products/realDelete/{id}', 'ProductController@realDelete')->name('products.realDelete');

    //image
    Route::resource('images', 'ImageController');
    Route::post('images/updateImages/{id}', 'ImageController@updateImages')->name('images.update');
    Route::post('images/uploadMultiImage', 'ImageController@postImage')->name('images.uploadMultiImage');

    //customer
    Route::resource('customers', 'CustomerController');
    Route::get('searchCustomers', 'CustomerController@search')->name('customers.search');

    //order
    Route::resource('orders', 'OrderController');
    Route::get('searchOrders', 'OrderController@search')->name('orders.search');

    //overview
    Route::post('overview/getOrdersOnDay', 'OverviewController@getResourcesOn')->name('overview.getOnDay');

});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Order extends Model
{
    protected $fillable = [
        'customer_id',
        'note',
        'total_cost',
    ];

    public function customer()
    {
        return $this->belongsTo('App\Customer');
    }

    public function products()
    {
        return $this->belongsToMany('App\Product')->withPivot('number_of_product')->withTimestamps();
    }

    public function getAllResource()
    {
        return $this->latest()->paginate(5);
    }

    /**
     * function attach of $order with arr product
     * @param $order
     * @param $products
     */
    public function attachPivotWith($order, $products)
    {
        foreach ($products as $product) {
            $order->products()->attach($product['id'], [
                'number_of_product' => $product['number_of'],
            ]);
        }
    }

    /**
     * function detach of $order with arr product
     * @param $order
     * @param $products
     */
    public function detachPivotWith($order, $products)
    {
        foreach ($products as $product) {
            $order->products()->detach($product->id);
        }
    }

    /**
     * @param $arr
     * @return \Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    public function getResourcesBy($arr)
    {
        $name = isset($arr['name']) ? $arr['name'] : null;
        $note = isset($arr['note']) ? $arr['note'] : null;
        $resources = DB::table('orders')
            ->join('customers', 'customers.id', '=', 'orders.customer_id')
            ->where('customers.name', 'like', '%' . $name . '%')
            ->where('orders.note', 'like', '%' . $note . '%')
            ->latest('orders.created_at')
            ->paginate(5);

        return $resources;
    }

    /**
     * @param $day
     * @return mixed
     */
    public function getOrdersOn($day)
    {
        return $this->whereDate('created_at', $day)->latest()->get();
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use App\Order;
use App\Product;
use App\Rules\IsntZero;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;

class OrderController extends Controller
{
    protected $order;
    protected $product;

    public function __construct(Order $order, Product $product)
    {
        $this->order = $order;
        $this->product = $product;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $resources = $this->order->getAllResource();
        return view('admins.orders.order', ['resources' => $resources]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        $customers = Customer::latest()->get();
        $products = Product::latest()->get();
        return view('admins.orders.createAndUpdate', ['customers' => $customers, 'products' => $products]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'customer' => 'required',
            'total_cost' => ['required', 'numeric', new IsntZero()],
            'products' => 'required',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'statusCode' => 500,
                'message' => 'Create order fail',
                'data' => $validator->errors()
            ], 500);
        } else {
            $orderData = [
                'customer_id' => $request->customer['id'],
                'note' => $request->note,
                'total_cost' => $request->total_cost
            ];
            $products = $request->products;
            $stringResponse = '';
            $check = false;
            foreach ($products as $product) {
                if (!$this->product->checkNumberOf($product['id'], $product['number_of'])) {
                    $check = false;
                    $stringResponse = 'The product has name ' . $product['name'] . ' not enough to sell';
                    break;
                } else $check = true;
            }
            if ($check) {
                foreach ($products as $product) {
                    $this->product->updateNumberOf($product['id'], $product['number_of']);
                }
                $order = $this->order->create($orderData);
                $this->order->attachPivotWith($order, $products);
                return response()->json([
                    'statusCode' => 200,
                    'message' => 'Create order successful',
                ], 200);
            } else
                return response()->json([
                    'statusCode' => 500,
                    'message' => $stringResponse
                ], 500);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Factory|View
     */
    public function edit($id)
    {
        $customers = Customer::latest()->get();
        $products = Product::latest()->get();
        $order = $this->order->findOrFail($id);
        return view('admins.orders.createAndUpdate', ['customers' => $customers, 'products' => $products, 'order' => $order]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return JsonResponse
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'total_cost' => ['required', 'numeric', new IsntZero()],
            'products' => 'required',
        ]);

        if ($validator->fails()) {
            return response()->json([
                'statusCode' => 500,
                'message' => 'Create order fail',
                'data' => $validator->errors()
            ], 500);
        } else {
            $orderData = [
                'note' => $request->note,
                'total_cost' => $request->total_cost
            ];
            $order = $this->order->findOrFail($id);
            $oldProductArr = $order->products()->get();
            foreach ($oldProductArr as $product) {
                $inventory = $this->product->findOrFail($product->id)->number_of;
                //update number of product : oldNumberOf + ( number of in order_product)
                $product->update(['number_of' => $inventory + $product->pivot->number_of_product]);
            }
            $this->order->detachPivotWith($order, $oldProductArr);
            $check = true;
            $stringResponse = '';
            $newProductArr = $request->products;
            foreach ($newProductArr as $product) {
                if (!$this->product->checkNumberOf($product['id'], $product['number_of'])) {
                    $check = false;
                    $stringResponse = 'The product has name ' . $product['name'] . ' not enough to sell';
                    break;
                }
            }
            if ($check) {
                foreach ($newProductArr as $product) {
                    $this->product->updateNumberOf($product['id'], $product['number_of']);
                }

                $this->order->attachPivotWith($order, $newProductArr);
                $order->update($orderData);
                return response()->json([
                    'statusCode' => 200,
                    'message' => 'Update order successful',
                    'data' => $order
                ], 200);
            } else {
                foreach ($oldProductArr as $product) {
                    $oldNumberOf = $product->number_of;
                    //update number of product : oldNumberOf - ( number of in order_product)
                    $product->update(['number_of' => $oldNumberOf - $product->pivot->number_of_product]);
                }
                return response()->json([
                    'statusCode' => 500,
                    'message' => $stringResponse
                ], 500);
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return JsonResponse
     */
    public function destroy($id)
    {
        $order= $this->order->destroy($id);
        return response()->json([
            'statusCode' => 200,
            'message' => 'Delete order successful',
            'data' => $order
        ], 200);
    }

    /**
     * @param Request $request
     * @return Factory|View
     */
    public function search(Request $request)
    {
        $request->flash();
        $resources = $this->order->getResourcesBy($request->all());
        return view('admins.orders.order', ['resources' => $resources]);
    }
}

resources/views/admins/orders/order.blade.php
@extends('admins.layout.master')

@section('title')
    Order
@endsection

@section('content')
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <a href="{{ route('orders.index') }}"><h3>Order</h3></a>
                    <div class="x_content">
                        <a href="{{ route('orders.create') }}" class="btn btn-success btn-xs"><i
                                class="fa fa-plus-square"></i> Add order</a>
                    </div>
                </div>
            </div>

            <div class="clearfix">
                <div class="x_content">
                    <form class="form-horizontal form-label-left input_mask" id="searchCategory"
                          action="{{ route('orders.search') }}" method="get">
                        <div class="col-md-5 col-sm-5 col-xs-6 form-group has-feedback inputSearch">
                            <p>Customer: </p>
                            <input type="text" class="form-control" id="inputSuccess2" placeholder="Name of customer" name="name" value="{{ old('name') }}">
                        </div>

                        <div class="col-md-5 col-sm-5 col-xs-6 form-group has-feedback inputSearch">
                            <p>Note: </p>
                            <input type="text" class="form-control" id="inputSuccess3" placeholder="Note"
                                   name="note" value="{{ old('note') }}">
                        </div>

                        <div class="form-group col-md-2 col-sm-2 col-xs-12 col-md-offset-3">
                            <div class="">
                                <button class="btn btn-primary" type="reset">Reset</button>
                                <button type="submit" class="btn btn-success" id="btnSearchCategory">Search</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="x_panel">
                        <div>
                            <h2>Products</h2>
                        </div>
                        <div class="x_content">
                            <!-- start project list -->
                            <table class="table table-striped projects">
                                <thead>
                                <tr>
                                    <th style="width: 1%">#</th>
                                    <th>Customer</th>
                                    <th>Created at</th>
                                    <th>Note</th>
                                    <th>Total cost</th>
                                    <th>#Edit</th>
                                </tr>
                                </thead>
                                <tbody class="tbody">
                                <?php $dem = 1 ?>
                                @foreach($resources as $resource)
                                    <tr>
                                        <th class="stt">{{$dem}}</th>
                                        <td class="tdName">
                                            @if(Request::route()->getName() == 'orders.search')
                                                <p class="tr-name-{{$resource->id}}">
                                                    <strong>{{$resource->name}}</strong></p>
                                            @endif
                                            @if(Request::route()->getName() != 'orders.search')
                                                <p class="tr-name-{{$resource->id}}">
                                                    <strong>{{$resource->customer->name}}</strong></p>
                                            @endif
                                        </td>
                                        <td>
                                            <p class="tr-created_at-{{$resource->id}}">{{$resource->created_at}}</p>
                                        </td>
                                        <td>
                                            <p class="tr-note-{{$resource->id}}">{{$resource->note}}</p>
                                        </td>
                                        <td>
                                            <p class="tr-total_cost-{{$resource->id}}">{{ number_format($resource->total_cost,2) }}
                                                đ</p>
                                        </td>
                                        <td class="tdEdit">
                                            <a href="{{ route('orders.edit',['order' => $resource->id]) }}"
                                               class="editBtn btn btn-info btn-xs">
                                                <i class="fa fa-pencil"></i> Edit
                                            </a>
                                            <button type="button" class="deleteBtn btn btn-danger btn-xs"
                                                    data_id="{{ $resource->id }}"><i
                                                    class="fa fa-trash-o"></i> Delete
                                            </button>
                                        </td>
                                    </tr>
                                    <?php $dem++; ?>
                                @endforeach
                                </tbody>
                            </table>
                            <!-- end project list -->
                            <div>{{ $resources->appends(Request::only('name', 'note'))->links() }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('build/js/order.js') }}"></script>
@endsection